
import java.text.DecimalFormat;
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jmc16
 */
public class ConversorMonedas extends javax.swing.JFrame {
    boolean eurToUsd = true;
    DecimalFormat df = new DecimalFormat("#.00");
    
    /**
     * Creates new form ConversorMonedas
     */
    public ConversorMonedas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCantidad = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        buttonConvertir = new javax.swing.JButton();
        textFactorConversion = new javax.swing.JTextField();
        labelEUR = new javax.swing.JLabel();
        buttonConversion = new javax.swing.JButton();
        textResultado = new javax.swing.JTextField();
        labelUSD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCantidad.setText("Cantidad:");

        buttonConvertir.setText("Convertir EUR a USD");
        buttonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertirActionPerformed(evt);
            }
        });

        labelEUR.setText("1 EUR =");

        buttonConversion.setText("Cambiar conversión");
        buttonConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConversionActionPerformed(evt);
            }
        });

        textResultado.setEditable(false);

        labelUSD.setText("USD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelEUR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFactorConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUSD))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(buttonConvertir)
                        .addGap(28, 28, 28)
                        .addComponent(buttonConversion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFactorConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEUR)
                    .addComponent(labelUSD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConvertir)
                    .addComponent(buttonConversion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertirActionPerformed
        double res;
        try{
            if(eurToUsd){
                res = conversion(Double.parseDouble(textFactorConversion.getText()), Double.parseDouble(textCantidad.getText()));
                textResultado.setText(df.format(res));
            }else{
                res = conversion((1/Double.parseDouble(textFactorConversion.getText())), Double.parseDouble(textCantidad.getText()));
                textResultado.setText(df.format(res));
            }
        }catch(NumberFormatException e){
            System.out.println("Uno de los campos introducidos no corresponde con un número decimal.");
            textResultado.setText("Input erróneo");
        }
        
    }//GEN-LAST:event_buttonConvertirActionPerformed

    private double conversion(double factor, double cantidad){
        return factor*cantidad;
    }
    
    private void buttonConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConversionActionPerformed
        if(eurToUsd){
            this.eurToUsd = false;
            this.buttonConvertir.setText("Convertir USD a EUR");
        }else{
            this.eurToUsd = true;
            this.buttonConvertir.setText("Convertir EUR a USD");
        }
        
    }//GEN-LAST:event_buttonConversionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorMonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConversion;
    private javax.swing.JButton buttonConvertir;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelEUR;
    private javax.swing.JLabel labelUSD;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textFactorConversion;
    private javax.swing.JTextField textResultado;
    // End of variables declaration//GEN-END:variables
}
